version: "3.9"
services:
  postgresql:
    container_name: postgresql
    image: supabase/postgres
    volumes:
      - ./volumes/db/realtime.sql:/docker-entrypoint-initdb.d/migrations/99-realtime.sql:Z
      # Must be superuser to create event trigger
      - ./volumes/db/webhooks.sql:/docker-entrypoint-initdb.d/init-scripts/98-webhooks.sql:Z
      # Must be superuser to alter reserved role
      - ./volumes/db/roles.sql:/docker-entrypoint-initdb.d/init-scripts/99-roles.sql:Z
      # PGDATA directory is persisted between restarts
      - ./volumes/db/data:/var/lib/postgresql/data:Z
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PORT=${POSTGRES_PORT}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - "5432:5432"
    networks:
      - net-translation-graph

  neo4j:
    container_name: neo4j
    image: neo4j
    environment:
      - NEO4J_AUTH="${NEO4J_USER}/${NEO4J_PASSWORD}"
      - NEO4JLABS_PLUGINS=${NEO4JLABS_PLUGINS}
    ports:
      - "7474:7474"
      - "7687:7687"
    volumes:
      - ./volumes/neo4j_data:/data
      - ./volumes/neo4j_logs:/logs
    networks:
      - net-translation-graph

  opensearch:
    container_name: opensearch
    image: opensearchproject/opensearch
    environment:
      - opensearch_security_plugin.dflt.password=mypassword
      - opensearch_security_plugin.dflt.username=myuser
      - cluster.name=${OPENSEARCH_CLUSTER_NAME}
      - node.name=${OPENSEARCH_NODE_NAME}
      - discovery.type=${OPENSEARCH_DISCOVERY_TYPE}
      - bootstrap.memory_lock=${OPENSEARCH_BS_MEMLOCK}
      - OPENSEARCH_JAVA_OPTS=${OPENSEARCH_JAVA_OPTS}
    ulimits:
      memlock:
        soft: -1
        hard: -1
    ports:
      - "9200:9200"
      - "9300:9300"
    volumes:
      - ./volumes/opensearch_data:/usr/share/opensearch/data
    networks:
      - net-translation-graph

  opensearch-dashboards:
    image: opensearchproject/opensearch-dashboards:latest
    container_name: opensearch-dashboards
    ports:
      - '5601:5601'
    volumes:
      - ./volumes/opensearch_dashboards_data:/usr/share/opensearch-dashboards/data
    environment:
      - OPENSEARCH_HOSTS=${OPENSEARCH_HOSTS}
      - DISABLE_INSTALL_DEMO_CONFIG=${DISABLE_INSTALL_DEMO_CONFIG}
    networks:
      - net-translation-graph
    depends_on:
      - opensearch

  pgadmin4:
    image: dpage/pgadmin4
    container_name: pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=${PGADMIN_DEFAULT_EMAIL}
      - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_DEFAULT_PASSWORD}
      - PGADMIN_LISTEN_PORT=${PGADMIN_LISTEN_PORT}
    ports:
      - "${PGADMIN_LISTEN_PORT}:${PGADMIN_LISTEN_PORT}"
    volumes:
      - ./volumes/pgadmin_data:/var/lib/pgadmin
    networks:
      - net-translation-graph
    depends_on:
      - postgresql

  ingest-frontend:
    image: streamlit/streamlit
    container_name: ingest-frontend
    volumes:
      - ./volumes/ingest-frontend:/app
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_HOST=${POSTGRES_HOST}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_PORT=${POSTGRES_PORT}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    command: streamlit run app.py
    ports:
      - "8501:8501"
    networks:
      - net-translation-graph
    depends_on:
      - postgresql

  search-frontend:
    image: streamlit/streamlit
    container_name: search-frontend
    volumes:
      - ./volumes/search-frontend:/app
    environment:
      - NEO4J_HOST=${NEO4J_HOST}
      - NEO4J_USER=${NEO4J_USER}
      - NEO4J_PASSWORD=${NEO4J_PASSWORD}
    command: streamlit run app.py
    ports:
      - "8502:8501"
    networks:
      - net-translation-graph
    depends_on:
      - neo4j

networks:
  net-translation-graph:
